// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYFECjdmj75pxUE949tsfNUViWmxuxwog',
    appId: '1:163616530376:web:b60c7363e3dcf84d7c2afd',
    messagingSenderId: '163616530376',
    projectId: 'eastern-rain-327713',
    authDomain: 'eastern-rain-327713.firebaseapp.com',
    storageBucket: 'eastern-rain-327713.appspot.com',
    measurementId: 'G-TX9FV2KFSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApQXCFeH_wAwHhVc4KDTT4fsXAApqLCys',
    appId: '1:163616530376:android:de6790eafc68f4057c2afd',
    messagingSenderId: '163616530376',
    projectId: 'eastern-rain-327713',
    storageBucket: 'eastern-rain-327713.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATROr1cp2LJTDWjgfeYaUhP0E06esj7lc',
    appId: '1:163616530376:ios:d8b8ef966196b08b7c2afd',
    messagingSenderId: '163616530376',
    projectId: 'eastern-rain-327713',
    storageBucket: 'eastern-rain-327713.appspot.com',
    iosClientId: '163616530376-j7jim7gr7k8igh0jdksuthkues69v79d.apps.googleusercontent.com',
    iosBundleId: 'com.example.remicare',
  );
}
